### PR TITLE
Allow for custom styles

### PR DESCRIPTION
**Pull request by ntatko**
Resolves: https://github.com/MonsantoCo/ol-kit/issues/93

### PR Safety Checklist:

 - [x] Added the task to the appropriate release doc under **Enhancements** or **Bug Fixes**
 - [ ] Bump `package.json` & `package-lock.json` version numbers to appropriate release
 - [ ] (optional) All external API changes have been documented
 - [ ] (optional) Build docs: `npm run docs`

### Quick Description of Changes (+ screenshots for ui changes):

Add a theme to your map app!

```JSX
import { createMuiTheme } from '@material-ui/core/styles';

<Map theme={createMuiTheme({
  palette: {
    type: 'dark',
    primary: {
       main: '#FF4500'
    }
  }
})} />
```

This applies a theme that applies to the whole app. The buttons are controlled by the primary palette color, and the other features (checkbox, tab indicator) use the secondary color
  
Screen Shot 2020-07-02 at 17 54 56
Screen Shot 2020-07-02 at 17 54 31
Screen Shot 2020-07-02 at 17 54 26
Screen Shot 2020-07-02 at 17 54 18

### CODE REVIEW

**Comment by glenselle** [comment]
I wish it wasn't this messy, but this does indeed work

**Comment by drodenberg** [comment]
Two things, I dont like using material-ui which this PR requires and I think connectToMap is just as fragile as passing props. We’ve definitely ran into issues of when to add the connectToMap to things just as much as props. If we go this route we are definitely dug deep into material-ui and it would be a nightmare to switch. Makes me nervous to merge just because of how much we would be invested into material-ui. I know we're pretty invested now but this just seems like another level

**Comment by drodenberg** [comment]
I honestly wish we would've started with something much lighter like this https://materializecss.com/about.html. I wish we just used css and didn't have to use material-ui.

**Comment by ntatko** [comment]
>  I dont like using material-ui which this PR requires

I agree with you, but the trouble is that you're currently depending on material UI for icons, styles, and components. You've already drunk the Kool-Aid, not sure this is the time to reconsider.

> I think connectToMap is just as fragile as passing props

Yes, that's true. But passing props is the other option that I see, and this seemed slightly _slightly_ more elegant.

I'm happy to pivot if we can find a better option.

**Comment by ntatko** [comment]
There's a chance that one high-level theme provider could work for all of the styled-components. Each styled component would still need to read `property: ${props => props.theme.property}`, but it's slightly better than wrapping everything in `connectToMap`

```jsx
import { ThemeProvider } from 'styled-components'
import { connectToMap } from 'Map'
// borrows from https://styled-components.com/docs/advanced#theming
export const styledWrapper = connectToMap((props) => {
  const { theme, children } = props;
  return (
    <ThemeProvider theme={theme}>
      { children }
    </ThemeProvider>
  )
})
```

**Comment by stazrad** [comment]
up for discussion- will not implement with material ui

**Pull request closed without merging**
